rmfd,charsets: remove unused struct field
    rmfd-charsets.c:577:5: error: missing initializer for field ‘charsize’ of ‘SubsetEntry’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
         { RMFD_MODEM_CHARSET_GSM,     gsm_is_subset },
         ^
    rmfd-charsets.c:573:11: note: ‘charsize’ declared here
         guint charsize;
               ^~~~~~~~
    rmfd-charsets.c:578:5: error: missing initializer for field ‘charsize’ of ‘SubsetEntry’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
         { RMFD_MODEM_CHARSET_IRA,     ira_is_subset },
         ^
    rmfd-charsets.c:573:11: note: ‘charsize’ declared here
         guint charsize;
               ^~~~~~~~
    rmfd-charsets.c:579:5: error: missing initializer for field ‘charsize’ of ‘SubsetEntry’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
         { RMFD_MODEM_CHARSET_UCS2,    ucs2_is_subset },
         ^
    rmfd-charsets.c:573:11: note: ‘charsize’ declared here
         guint charsize;
               ^~~~~~~~
    rmfd-charsets.c:580:5: error: missing initializer for field ‘charsize’ of ‘SubsetEntry’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
         { RMFD_MODEM_CHARSET_8859_1,  iso88591_is_subset },
         ^
    rmfd-charsets.c:573:11: note: ‘charsize’ declared here
         guint charsize;
               ^~~~~~~~
    rmfd-charsets.c:581:5: error: missing initializer for field ‘charsize’ of ‘SubsetEntry’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
         { RMFD_MODEM_CHARSET_PCCP437, pccp437_is_subset },
         ^
    rmfd-charsets.c:573:11: note: ‘charsize’ declared here
         guint charsize;
               ^~~~~~~~
    rmfd-charsets.c:582:5: error: missing initializer for field ‘charsize’ of ‘SubsetEntry’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
         { RMFD_MODEM_CHARSET_PCDN,    pcdn_is_subset },
         ^
    rmfd-charsets.c:573:11: note: ‘charsize’ declared here
         guint charsize;
               ^~~~~~~~
    rmfd-charsets.c:583:5: error: missing initializer for field ‘charsize’ of ‘SubsetEntry’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
         { RMFD_MODEM_CHARSET_UNKNOWN, NULL },
         ^
    rmfd-charsets.c:573:11: note: ‘charsize’ declared here
         guint charsize;
               ^~~~~~~~