rmfd: require explicit object casts in g_object_ref ()
    rmfd-port-data-wwan.c: In function ‘setup’:
    rmfd-port-data-wwan.c:106:15: error: assignment to ‘RmfdPortDataWwan *’ {aka ‘struct _RmfdPortDataWwan *’} from incompatible pointer type ‘RmfdPortData *’ {aka ‘struct _RmfdPortData *’} [-Werror=incompatible-pointer-types]
         ctx->self = g_object_ref (self);
                   ^
    cc1: all warnings being treated as errors
    make[5]: *** [Makefile:877: rmfd-rmfd-port-data-wwan.o] Error 1
    make[5]: *** Waiting for unfinished jobs....
    rmfd-port-processor-qmi.c: In function ‘run’:
    rmfd-port-processor-qmi.c:3712:15: error: assignment to ‘RmfdPortProcessorQmi *’ {aka ‘struct _RmfdPortProcessorQmi *’} from incompatible pointer type ‘RmfdPortProcessor *’ {aka ‘struct _RmfdPortProcessor *’} [-Werror=incompatible-pointer-types]
         ctx->self = g_object_ref (self);
                   ^
    rmfd-port-processor-qmi.c: In function ‘messaging_event_report_indication_cb’:
    rmfd-port-processor-qmi.c:3973:21: error: assignment to ‘QmiClientWms *’ {aka ‘struct _QmiClientWms *’} from incompatible pointer type ‘QmiClientNas *’ {aka ‘struct _QmiClientNas *’} [-Werror=incompatible-pointer-types]
             ctx->client = g_object_ref (client);
                         ^
    rmfd-port-processor-qmi.c: In function ‘initable_init_async’:
    rmfd-port-processor-qmi.c:5057:15: error: assignment to ‘RmfdPortProcessorQmi *’ {aka ‘struct _RmfdPortProcessorQmi *’} from incompatible pointer type ‘GAsyncInitable *’ {aka ‘struct _GAsyncInitable *’} [-Werror=incompatible-pointer-types]
         ctx->self = g_object_ref (initable);
                   ^