build: require explicit glib 2.32 symbols
  rmfd-port.c: In function ‘rmfd_port_init’:
  rmfd-port.c:56:13: error: G_ADD_PRIVATE [-Werror]
     56 |     self->priv = G_TYPE_INSTANCE_GET_PRIVATE (self, RMFD_TYPE_PORT, RmfdPortPrivate);
        |             ^~~~~~~~~~~~~~~
    CC       rmfd-rmfd-port-data.o
  cc1: all warnings being treated as errors