rmfd,manager: add missing headers
rmfd-manager.c: In function 'setup_socket_service':
rmfd-manager.c:576: warning: implicit declaration of function 'g_unlink'