rmfd,utils: add missing headers
rmfd-utils.c: In function 'rmfd_utils_get_mnc_length_for_mcc':
rmfd-utils.c:36: warning: implicit declaration of function 'atoi'
rmfd-utils.c: In function 'rmfd_utils_peek_physical_device':
rmfd-utils.c:132: warning: implicit declaration of function 'strcmp'